config/routes.rb
Happiness::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :surveys, only: [:index, :create, :show] do
    resources :survey_questions, only: [:index, :create, :show, :update]
  end

  resource :home, only: [:index]
  resources :charts, only: [:show]
  root to: 'surveys#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Happiness
    %meta(name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css", :rel => "stylesheet"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body(ng-app="app")
    %nav.navbar.navbar-default{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => ".collapse.navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Happiness Log
        .collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li= link_to 'Surveys', surveys_path
              %li= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-link'
            - else
              %li= link_to 'Sign in', new_user_session_path
              %li= link_to 'Sign up', new_user_registration_path

    = flash[:error]
    = yield
    %script{:src => "//code.jquery.com/jquery-1.11.0.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}
    = javascript_include_tag "application"